import Head from 'next/head';
import Footer from '../components/footer';
import Header from '../components/header';
import Main from '../components/main';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Monochrome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="//db.onlinewebfonts.com/c/9ecec61376083fd290b75d94fdaca380?family=Baskerville+Old+Face"
          rel="stylesheet"
          type="text/css"
        />
      </Head>

      <Header></Header>

      <Main></Main>

      <Footer></Footer>
    </div>
  );
}
